[people-colors]
ode = "f1c40f"
Crouton = "b925ee"
Pupper = "35bb3e"
theBeef = "3682fa"
dylwalk = "61acd6"
Sirobot = "e91e63"
Washingdone = "f7cac9"
KyroZed = "009473"
Thy = "ffc1a1"
Naldy = "ff5ca7"

[chart]
daysLimit = 365
rankChartTitle = "XP History"
bg = "26282a"
fontColor = "e5e5e5"
axesColor = "eeeeee"
axesFontSize = 5
titleFontSize = 8
seriesStrokeWidth = 3
height = 1000
width = 2000
dpi = 300
tickNum = 10
milestones = [
    {name = "Novice", xp = 2000},
    {name = "Apprentice", xp = 4000},
    {name = "Established", xp = 8000},
    {name = "Seasoned", xp = 16000},
    {name = "Distinguished", xp = 32000},
    {name = "Eminent", xp = 64000},
    {name = "Mythic", xp = 128000},
    {name = "Transcendent", xp = 256000},
    {name = "Celestial", xp = 512000},
    {name = "Empyreal", xp = 1024000}
]
